### ISSUE TITLE
Edit hexathon fields

### ISSUE THREAD

**Issue by Roshan-D** [HackGT/registration2#113]

**Comment by Roshan-D** [comment]
On the `Select Event` page, add functionality to be able to edit the hexathon.
<img width="190" alt="Screenshot 2023-03-15 at 2 37 58 PM" src="https://user-images.githubusercontent.com/38771624/225409659-1338a791-74df-4edd-869c-f14331168da5.png">

**Comment by thaneesh-babu** [comment]
Feel free to decide how you would like to display the edit option for each hexathon but you can take inspiration from the way we're able to edit blocks in the [live site](https://live.hexlabs.org/), keeping in mind that such an option can't be on the event cards since it's already clickable. Only admins should be able to see the edit option.
